### ISSUE TITLE
Usage Question

### ISSUE THREAD

**Issue by itssidhere** [hate-alert/IndicAbusive#2]
Is the input to the model in Hinglish or in pure hindi? As the content on the web is mainly in Hinglish.

For example, will it work for "Aur Kaisa hai" or "और कैसा है"

**Comment by das-mithun** [comment]
The following model is trained with both kinds of languages. So it should work for Hinglish and pure Hindi data. https://huggingface.co/Hate-speech-CNERG/indic-abusive-allInOne-MuRIL .
